#pragma once

// Motores 
#define MOTOR1_PWM_PIN 22
#define MOTOR2_PWM_PIN 23


// LED
#define LED1_PIN


// MULTIPLEX
#define MUX_S0_PIN 12
#define MUX_S1_PIN 13
#define MUX_S2_PIN 14
#define MUX_S3_PIN 27
#define MUX_Z 26


// REGULADOR DE TENSÃO
#define REGULADOR_TENSAO 21


// JOYSTICK
#define JOYSTICK_DIR_Y ADC_CHANNEL_5  // GPIO 33
#define JOYSTICK_DIR_X ADC_CHANNEL_4  // GPIO 32
#define JOYSTICK_DIR_BTN  GPIO_NUM_19 // GPIO 19

#define JOYSTICK_ESQ_Y ADC_CHANNEL_7  // GPIO 35
#define JOYSTICK_ESQ_X ADC_CHANNEL_6  // GPIO 34
#define JOYSTICK_ESQ_BTN  GPIO_NUM_18 // GPIO 18